- name: Add deadsnakes repository
  become: true
  apt_repository:
    repo: ppa:deadsnakes/ppa
  when: ansible_distribution == 'Ubuntu'

- name: Install Python 3.11
  become: true
  package:
    name: python3.11
    state: present

- name: Install Venv
  become: true
  shell: yes 'y' | sudo apt install python3.11-venv
  args:
    executable: /bin/bash
